# Generated by Django 3.2.3 on 2021-06-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0002_gaminglaptop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaminglaptop',
            name='summary',
        ),
        migrations.AddField(
            model_name='gaminglaptop',
            name='forwardlink',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='gaminglaptop',
            name='laptopname',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='gaminglaptop',
            name='photolink',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='gaminglaptop',
            name='price',
            field=models.IntegerField(null=True, blank=True, default=None),
        ),
    ]
