# Generated by Django 3.2.3 on 2021-06-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0005_alter_gaminglaptop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaminglaptop',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
