# Generated by Django 3.2.3 on 2021-06-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0006_alter_gaminglaptop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaminglaptop',
            name='forwardlink',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='gaminglaptop',
            name='laptopname',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='gaminglaptop',
            name='photolink',
            field=models.URLField(default=''),
        ),
    ]
