# Generated by Django 3.2.3 on 2021-06-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0007_auto_20210612_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwardlink', models.URLField(default='')),
                ('photolink', models.URLField(default='')),
                ('mobilename', models.TextField(default='', max_length=150)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
