# Generated by Django 3.2.3 on 2021-06-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0008_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mobile',
            new_name='homepagemobile',
        ),
    ]
