# Generated by Django 3.2.3 on 2021-06-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0009_rename_mobile_homepagemobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='acer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwardlink', models.URLField(default='')),
                ('photolink', models.URLField(default='')),
                ('laptopname', models.TextField(default='', max_length=150)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('site', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='alllaptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwardlink', models.URLField(default='')),
                ('photolink', models.URLField(default='')),
                ('laptopname', models.TextField(default='', max_length=150)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('site', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='apple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwardlink', models.URLField(default='')),
                ('photolink', models.URLField(default='')),
                ('laptopname', models.TextField(default='', max_length=150)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('site', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='asus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwardlink', models.URLField(default='')),
                ('photolink', models.URLField(default='')),
                ('laptopname', models.TextField(default='', max_length=150)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('site', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwardlink', models.URLField(default='')),
                ('photolink', models.URLField(default='')),
                ('laptopname', models.TextField(default='', max_length=150)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('site', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwardlink', models.URLField(default='')),
                ('photolink', models.URLField(default='')),
                ('laptopname', models.TextField(default='', max_length=150)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('site', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='msi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwardlink', models.URLField(default='')),
                ('photolink', models.URLField(default='')),
                ('laptopname', models.TextField(default='', max_length=150)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('site', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='razerblade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwardlink', models.URLField(default='')),
                ('photolink', models.URLField(default='')),
                ('laptopname', models.TextField(default='', max_length=150)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('site', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
