# Generated by Django 3.2.3 on 2021-08-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0015_latestflagship'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaminglaptop',
            name='site',
            field=models.CharField(default='', max_length=20),
        ),
    ]
